# Generated by Django 5.0.4 on 2024-06-09 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zone',
            old_name='name',
            new_name='zone_name',
        ),
    ]
