# Generated by Django 5.0.4 on 2024-06-09 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_app', '0002_rename_name_zone_zone_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
                ('from_zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_zone', to='log_app.zone')),
            ],
        ),
    ]
